---
title: "test_particle_filter"
author: "Alessio Zakaria"
date: "21 May 2020"
output: pdf_document
---

```{r}
library(RcppArmadillo)
library(Rcpp)
library(pomp)
library(ParticleFilter)
```

```{r}
library(pomp)

sir_step <- pomp::Csnippet("
  double N = 763;
  double dN_SI = rbinom(S,1-exp(-(Beta*I*dt)/N));
  double dN_IR = rbinom(I,1-exp(-gamma*dt));
  S -= dN_SI;
  I += dN_SI - dN_IR;
  R += dN_IR;
")

rmeas  <- pomp::Csnippet("B = rpois(rho * I+1e-6);")

dmeas <- pomp::Csnippet("
  lik = dpois(B, rho*I+1e-6, give_log);
")
  
sir_init <- pomp::Csnippet("
  S = 762;
  I = 1;
  R = 0;
")

sir <- pomp(subset(bsflu, select=-C),
     times="day", 
     t0=0, 
     rprocess=euler(sir_step, delta.t=1), 
     rinit = sir_init, 
     rmeasure= rmeas, 
     dmeasure=dmeas,
     statenames=c("S", "I", "R"),
     paramnames = c("Beta", "gamma", "rho")
   )
```

```{r}
pf <-  logLik(pfilter(sir, Np=1000, params=c(Beta=1, rho=1, gamma=1)))
```



Generate data
```{r}
n <- 763

#y <- sample.int(100, n, replace = TRUE)
#df <- data.frame(B=y, tim = seq(n))

nparticles <-  10000000
initial_state <- c(n-1, 1, 0)
params <- c(n, 1, 1, 1, 1)
```

```{r}
#sourceCpp("/home/alessio/Documents/uni/phd/sc2/particle-filter/particle.cpp") #sourceCpp("/home/alessio/Documents/uni/phd/sc2/particle-filter/particlepar.cpp")
```


```{r}
start_profiler("/tmp/prof.out")
parParticleFilterCpp(bsflu$B, params, nparticles, initial_state, 4)
stop_profiler()
```



```{r}
#particleFilterCppPar(bsflu$B, params, nparticles, initial_state)
 
#p <- vector()
q <- vector()
t <- vector()
#v <- vector()
for(i in 1:100){
#  p[[i]] <- particleFilterCpp(bsflu$B, params, nparticles, initial_state)
#  q[[i]] <- particleFilterCpp(bsflu$B, params, nparticles, initial_state)
   t[[i]] <- parParticleFilterCpp(bsflu$B, params, nparticles, initial_state, 3)
#  v[[i]] <- logLik(pfilter(sir, Np=nparticles, params=c(Beta=1, rho=1, gamma=1)))
}
#par(mfrow=c(2,1))
plot(density(t), main="dqrng")
#plot(density(p), main="R API")
parParticleFilterCpp(bsflu$B, params, nparticles, initial_state, 3)
```

  
```{r}
q <- vector()
p <- vector()
for(i in 1:3000){
  q[[i]] <- particleFilterCpp(bsflu$B, params, nparticles, initial_state)
  p[[i]] <- particleFilterCppPar(bsflu$B, params, nparticles, initial_state)
}
par(mfrow=c(2,1))
plot(density(q))
plot(density(p))
```
```{r}
particleFilterCppPar(bsflu$B, params, nparticles, initial_state)
```

```{r}
particleFilterCppPar(bsflu$B, params, nparticles, initial_state)
```




```{r}
pfCpp <- function(n, nparticles) {
   v <- vector() 
   for(i in 1:n) {
     v[[i]] <- particleFilterCpp(pomp::bsflu$B, params, nparticles, initial_state)
   }
   return(v)
}
```

```{r}
pfCppPar <- function(n, nparticles) {
  v <- vector()
  for(i in 1:n) {
    v[[i]] <- parParticleFilterCpp(pomp::bsflu$B, params, nparticles, initial_state, 2)
  }
  return(v)
}
```




```{r}
library(microbenchmark)
microbenchmark(pfCpp(1, 1000), pfCppPar(1,1000))
```
  
  
```{r}
evalCpp(k)
```
