# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parParticleFilterCpp <- function(y, params, n_particles, initialState, ncores) {
    .Call(`_ParticleFilter_parParticleFilter`, y, params, n_particles, initialState, ncores)
}

particleFilterCpp <- function(y, params, n_particles, initialState) {
    .Call(`_ParticleFilter_particleFilter`, y, params, n_particles, initialState)
}

start_profiler <- function(str) {
    .Call(`_ParticleFilter_start_profiler`, str)
}

stop_profiler <- function() {
    .Call(`_ParticleFilter_stop_profiler`)
}

